import type { Metadata } from "next";

import Link from "next/link";
import { notFound } from "next/navigation";

import { JsonLd } from "../../../components/JsonLd";
import { LastModified } from "../../../components/LastModified";
import { Markdown } from "../../../components/Markdown";
import { OpenChatButton } from "../../../components/OpenChatButton";
import { RelatedContent } from "../../../components/RelatedContent";
import { RelatedTweets } from "../../../components/RelatedTweets";
import { SeeAlso } from "../../../components/SeeAlso";
import { AuthorInfo } from "../../../components/AuthorInfo";
import { TableOfContents } from "../../../components/TableOfContents";
import { getPaaAnswerContent } from "../../../lib/contentGen";
import { getCustomQa } from "../../../lib/customQa";
import {
  getPaaIndex,
  getTopQuestionSlugs,
  findPaaQuestion,
  getClusterIndex,
} from "../../../lib/indexes";
import { generateQaMetadata } from "../../../lib/seo";
import {
  generateBreadcrumbSchema,
  generateFaqPageSchema,
  generateQaPageSchema,
  generateWebPageSchema,
  generateHowToSchema,
  extractHowToStepsFromMarkdown,
  isHowToContent,
} from "../../../lib/structuredData";
import { getDynamicVariables } from "../../../lib/variables";

export const revalidate = 3600;

export async function generateStaticParams() {
  const slugs = await getTopQuestionSlugs();
  return slugs.map((slug) => ({ slug }));
}

export async function generateMetadata({
  params,
}: {
  params: { slug: string };
}): Promise<Metadata> {
  const q = await findPaaQuestion(params.slug);
  if (!q) {
    const custom = await getCustomQa(params.slug);
    if (!custom)
      return {
        title: "Question not found",
        robots: { index: false },
      };
    return generateQaMetadata({
      question: custom.question,
      slug: custom.slug,
    });
  }
  return generateQaMetadata({
    question: q.question,
    answer: q.answer,
    slug: q.slug,
    volume: q.volume,
  });
}

export default async function QuestionPage({
  params,
}: {
  params: { slug: string };
}) {
  const [q, custom, vars, paa, cluster] = await Promise.all([
    findPaaQuestion(params.slug),
    getCustomQa(params.slug),
    getDynamicVariables(),
    getPaaIndex(),
    getClusterIndex(),
  ]);

  if (!q && !custom) return notFound();

  const questionText = q?.question ?? custom?.question ?? "";
  const keywords = extractKeywords(questionText);
  const relevantTopics = findRelevantTopics(keywords, cluster.topics);

  if (!q && custom) {
    // JSON-LD for custom Q&A
    const jsonLd = [
      generateWebPageSchema({
        title: custom.question,
        description:
          "A chat-derived Q&A page from ElonGoat — generated by ElonSim (an AI simulation) with verification notes.",
        url: `/q/${custom.slug}`,
        dateModified: custom.updatedAt,
        breadcrumbs: [
          { name: "Home", url: "/" },
          { name: "Q&A", url: "/q" },
          { name: custom.question.slice(0, 30), url: `/q/${custom.slug}` },
        ],
      }),
      generateQaPageSchema({
        question: custom.question,
        answer: custom.answerMd.slice(0, 500),
        url: `/q/${custom.slug}`,
        createdAt: custom.createdAt,
      }),
      generateBreadcrumbSchema([
        { name: "Home", url: "/" },
        { name: "Q&A", url: "/q" },
        { name: custom.question.slice(0, 30), url: `/q/${custom.slug}` },
      ]),
    ];

    return (
      <>
        <JsonLd data={jsonLd} />
        <article className="space-y-6">
          <header className="glass glow-ring rounded-3xl p-6">
            <div className="flex flex-wrap items-center gap-2 text-xs text-white/60">
              <Link href="/q" className="hover:text-white">
                Q&A
              </Link>
              <span className="text-white/30">/</span>
              <span className="text-white/80">{custom.slug}</span>
            </div>
            <h1 className="mt-3 text-balance text-3xl font-semibold tracking-tight text-white md:text-4xl">
              {custom.question}
            </h1>
            <p className="mt-2 max-w-3xl text-sm text-white/65">
              This page was derived from real user questions and generated by
              ElonSim (an AI simulation). Variables: age {vars.age}, children{" "}
              {vars.children_count}.
            </p>

            <div className="mt-5 flex flex-col gap-3 sm:flex-row">
              <OpenChatButton
                label="Ask ElonSim a follow-up"
                className="inline-flex items-center justify-center gap-2 rounded-2xl bg-white px-5 py-3 text-sm font-semibold text-black transition hover:bg-white/90"
              />
            </div>
          </header>

          <section className="glass rounded-3xl p-6">
            <div className="flex flex-wrap items-center justify-between gap-3">
              <h2 className="text-lg font-semibold text-white">Answer</h2>
              <div className="text-xs text-white/50">
                Model: {custom.model ?? "unknown"} • Updated{" "}
                {new Date(custom.updatedAt).toLocaleString()}
              </div>
            </div>
            <div className="mt-4">
              <Markdown content={custom.answerMd} />
            </div>
          </section>

          <RelatedTweets
            keywords={keywords
              .split(" ")
              .filter((w) => w.length > 3)
              .slice(0, 5)}
            limit={3}
            title="What Elon said about this"
          />

          <RelatedContent
            type="qa"
            questionText={questionText}
            currentSlug={params.slug}
          />

          <SeeAlso type="qa" keywords={keywords} currentSlug={params.slug} />

          <AuthorInfo lastUpdated={custom.updatedAt} contentType="custom" />
        </article>
      </>
    );
  }

  const ai = await getPaaAnswerContent({ slug: q!.slug });

  const siblings = paa.questions
    .filter(
      (x) =>
        x.parent && q!.parent && x.parent === q!.parent && x.slug !== q!.slug,
    )
    .slice(0, 8);

  // Build FAQ items from siblings for FAQ schema
  const faqItems = siblings
    .filter((s) => s.answer)
    .slice(0, 5)
    .map((s) => ({
      question: s.question,
      answer: s.answer!,
    }));

  // Check if content is HowTo-style
  const contentIsHowTo = isHowToContent(ai.contentMd, q!.question);
  const howToSteps = contentIsHowTo
    ? extractHowToStepsFromMarkdown(ai.contentMd)
    : [];

  // JSON-LD for PAA questions
  const jsonLd: Record<string, unknown>[] = [
    generateWebPageSchema({
      title: q!.question,
      description:
        q!.answer ??
        "A People Also Ask question about Elon Musk — open it, see sources, and ask the AI for a deeper answer.",
      url: `/q/${q!.slug}`,
      dateModified: new Date(paa.generatedAt).toISOString(),
      breadcrumbs: [
        { name: "Home", url: "/" },
        { name: "Q&A", url: "/q" },
        { name: q!.question.slice(0, 30), url: `/q/${q!.slug}` },
      ],
    }),
    generateQaPageSchema({
      question: q!.question,
      answer: q!.answer ?? "Use the chat to generate an answer.",
      url: `/q/${q!.slug}`,
      createdAt: new Date(paa.generatedAt).toISOString(),
    }),
    generateBreadcrumbSchema([
      { name: "Home", url: "/" },
      { name: "Q&A", url: "/q" },
      { name: q!.question.slice(0, 30), url: `/q/${q!.slug}` },
    ]),
  ];

  // Add FAQ schema if there are related questions with answers
  if (faqItems.length >= 2) {
    jsonLd.push(
      generateFaqPageSchema([
        {
          question: q!.question,
          answer: q!.answer ?? ai.contentMd.slice(0, 500),
        },
        ...faqItems,
      ]),
    );
  }

  // Add HowTo schema if content has steps
  if (contentIsHowTo && howToSteps.length >= 2) {
    jsonLd.push(
      generateHowToSchema({
        name: q!.question,
        description: q!.answer ?? `Step-by-step guide: ${q!.question}`,
        url: `/q/${q!.slug}`,
        steps: howToSteps,
      }),
    );
  }

  const sourceHref = normalizeSourceUrl(q!.sourceUrl);

  return (
    <>
      <JsonLd data={jsonLd} />
      <article className="space-y-6">
        <header className="glass glow-ring rounded-3xl p-6">
          <div className="flex flex-wrap items-center gap-2 text-xs text-white/60">
            <Link href="/q" className="hover:text-white">
              Q&A
            </Link>
            <span className="text-white/30">/</span>
            <span className="text-white/80">{q!.slug}</span>
          </div>
          <h1 className="mt-3 text-balance text-3xl font-semibold tracking-tight text-white md:text-4xl">
            {q!.question}
          </h1>
          <p className="mt-2 max-w-3xl text-sm text-white/65">
            Fast variables: age {vars.age}, children {vars.children_count}. For
            deeper nuance, open the chat.
          </p>
          <LastModified date={paa.generatedAt} className="mt-3" />

          <div className="mt-5 flex flex-col gap-3 sm:flex-row">
            <OpenChatButton
              label="Ask the AI for a better answer"
              className="inline-flex items-center justify-center gap-2 rounded-2xl bg-white px-5 py-3 text-sm font-semibold text-black transition hover:bg-white/90"
            />
            {sourceHref ? (
              <a
                href={sourceHref}
                target="_blank"
                rel="noreferrer"
                className="inline-flex items-center justify-center gap-2 rounded-2xl border border-white/15 bg-white/5 px-5 py-3 text-sm font-semibold text-white/90 transition hover:bg-white/10"
              >
                View source
              </a>
            ) : null}
          </div>
        </header>

        <section className="glass rounded-3xl p-6">
          <h2 className="text-lg font-semibold text-white">Snippet</h2>
          <p className="mt-3 whitespace-pre-wrap text-sm leading-relaxed text-white/75">
            {q!.answer ??
              "No snippet was captured for this result. Use the chat to generate an answer."}
          </p>

          {q!.sourceTitle || q!.sourceUrl ? (
            <div className="mt-5 text-xs text-white/55">
              Source:{" "}
              {sourceHref ? (
                <a
                  href={sourceHref}
                  target="_blank"
                  rel="noreferrer"
                  className="text-white/80 hover:underline"
                >
                  {q!.sourceTitle ?? q!.sourceUrl}
                </a>
              ) : (
                <span>{q!.sourceTitle ?? q!.sourceUrl}</span>
              )}
            </div>
          ) : null}
        </section>

        <section className="glass rounded-3xl p-6">
          <div className="flex flex-wrap items-center justify-between gap-3">
            <h2 className="text-lg font-semibold text-white">
              AI expanded answer
            </h2>
            <div className="text-xs text-white/50">
              Model: {ai.model}
              {ai.cached ? " • cached" : ""}
            </div>
          </div>
          <div className="mt-4 grid gap-6 lg:grid-cols-[1fr,280px]">
            <div className="prose prose-invert prose-sm max-w-none">
              <Markdown content={ai.contentMd} />
            </div>
            <aside className="hidden lg:block">
              <TableOfContents contentSelector=".prose" minItems={3} />
            </aside>
          </div>
        </section>

        {siblings.length ? (
          <section className="glass rounded-3xl p-6">
            <h2 className="text-lg font-semibold text-white">
              Related questions
            </h2>
            <div className="mt-4 grid gap-3 md:grid-cols-2">
              {siblings.map((s) => (
                <Link
                  key={s.slug}
                  href={`/q/${s.slug}`}
                  className="rounded-2xl border border-white/10 bg-white/5 p-4 transition hover:border-white/20 hover:bg-white/10"
                >
                  <div className="text-sm font-semibold text-white">
                    {s.question}
                  </div>
                </Link>
              ))}
            </div>
          </section>
        ) : null}

        {/* Explore more section - links to relevant topics */}
        {relevantTopics.length > 0 && (
          <section className="glass rounded-3xl p-6">
            <h2 className="text-lg font-semibold text-white">
              Explore more about
            </h2>
            <p className="mt-2 text-sm text-white/60">
              Browse topic hubs related to this question
            </p>
            <div className="mt-4 flex flex-wrap gap-2">
              {relevantTopics.map((topic) => (
                <Link
                  key={topic.slug}
                  href={`/${topic.slug}`}
                  className="inline-flex items-center gap-1.5 rounded-xl border border-white/10 bg-white/5 px-4 py-2 text-sm text-white/80 transition hover:border-white/20 hover:bg-white/10 hover:text-white"
                >
                  {topic.topic}
                  <span className="text-xs text-white/50">
                    ({topic.pageCount})
                  </span>
                </Link>
              ))}
            </div>
          </section>
        )}

        <RelatedTweets
          keywords={keywords
            .split(" ")
            .filter((w) => w.length > 3)
            .slice(0, 5)}
          limit={3}
          title="What Elon said about this"
        />

        <RelatedContent
          type="qa"
          questionText={questionText}
          currentSlug={params.slug}
        />

        <SeeAlso type="qa" keywords={keywords} currentSlug={params.slug} />

        <AuthorInfo lastUpdated={paa.generatedAt} contentType="qa" />
      </article>
    </>
  );
}

function normalizeSourceUrl(url?: string | null): string | null {
  if (!url) return null;
  const trimmed = url.trim();
  if (!trimmed) return null;
  if (trimmed.startsWith("http://") || trimmed.startsWith("https://"))
    return trimmed;
  if (trimmed.startsWith("/search?")) return `https://www.google.com${trimmed}`;
  if (trimmed.startsWith("/")) return null;
  return null;
}

/**
 * Extract keywords from question text
 */
function extractKeywords(text: string): string {
  const stopWords = new Set([
    "the",
    "a",
    "an",
    "is",
    "are",
    "was",
    "were",
    "be",
    "been",
    "being",
    "have",
    "has",
    "had",
    "do",
    "does",
    "did",
    "will",
    "would",
    "could",
    "should",
    "may",
    "might",
    "must",
    "shall",
    "can",
    "need",
    "what",
    "when",
    "where",
    "who",
    "why",
    "how",
    "much",
    "many",
    "this",
    "that",
  ]);

  return text
    .toLowerCase()
    .replace(/[?'"]/g, "")
    .split(/\s+/)
    .filter((w) => w.length > 2 && !stopWords.has(w))
    .join(" ");
}

/**
 * Find relevant topics based on keywords
 */
function findRelevantTopics(
  keywords: string,
  topics: Array<{ slug: string; topic: string; pageCount: number }>,
): Array<{ slug: string; topic: string; pageCount: number }> {
  const keywordSet = new Set(keywords.split(/\s+/));

  return topics
    .map((topic) => {
      const topicLower = topic.topic.toLowerCase();
      const matchCount = [...keywordSet].filter((k) =>
        topicLower.includes(k),
      ).length;
      return { topic, matchCount };
    })
    .filter((x) => x.matchCount > 0)
    .sort((a, b) => b.matchCount - a.matchCount)
    .slice(0, 6)
    .map((x) => x.topic);
}
